name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  device_preview: ^1.2.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  adaptive_theme: ^3.6.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  fl_chart: ^0.69.2
  star_menu: ^4.0.1
  shared_preferences: ^2.3.4
  water_drop_nav_bar: ^2.2.2
  d_chart: ^2.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background_image/backgroundImage.png
    - assets/company_logo/logo.png
